### ISSUE TITLE
Update Guard version

### ISSUE THREAD

**Issue by cvkef** [meagar/guard-coffeelint#6]
Hey @meagar 

Is the project still alive? Could you please update deps version?

Thanks,
cvkef

**Comment by meagar** [comment]
Fixed, tested, pushing new gem 0.1.0

**Comment by meagar** [comment]
https://rubygems.org/gems/guard-coffeelint

**Comment by meagar** [comment]
Aaaand straight to 0.1.1, as I included a `binding.pry` in 0.1.0. Oops.

**Comment by cvkef** [comment]
:+1: Much appreciated!
